# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true

jobs:
- job: Build
  timeoutInMinutes: 90
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    imageName: 'quarkus:$(build.buildId)'  
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      TargetFolder:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'